feat: add support for adding task in a section
HipsterBrown/send-to-todoist pull request #17
Opened 2024-05-27 13:57 UTC by Schnouki

This PR makes it possible to add a task directly to a section in a project, instead of just adding it to a project without a section.

To do this, I also slightly rewrote how menu item IDs are handled: they are now always `${projectId}-${dueDate}` or `${projectId}-${dueDate}-${sectionId}`.

---
Quick disclaimers:
- I'm not a JS dev, I hope I didn't do anything stupid 😅
- Only tested in Firefox
- I work for Doist on the Todoist Backend, but this work isn't supported or endorsed by Doist.

2024-05-28 14:39 UTC, HipsterBrown requested changes
Thanks for creating this PR! This was definitely on my list of features, so I appreciate the contribution. One suggested change, otherwise this is looking great. 😄

2024-05-28 14:39 UTC, HipsterBrown commented on background_scripts/background.js
> +        .forEach(({ id: sectionId, name: sectionName }, sectionIndex) => {
I really like how quick it can be to add these sections. 👏 I think it would be visually helpful to add a separator between the due date menu items and section menu items. 

I also think we could optimize this slightly so projects that don't have any sections don't need to iterate through the list of sections by creating a dictionary/map of `projectId: [section]` ahead of time. Something like:

```js
  const projectSections = sections.reduce((result, section) => {
    if (result[section.project_id]) {
      result[section.project_id].push(section);
    } else {
      result[section.project_id] = [section];
    }
    return result;
  }, {})
```

Then the logic within each project would look like:

```js
      if (projectSections[id]) {
        browser.menus.create({
          contexts,
          id: `${parentId}-section-separator`,
          type: "separator",
          parentId
        });

        projectSections[id]
          .sort((a, b) => a.order - b.order)
          .forEach(({ id: sectionId, name: sectionName }, sectionIndex) => {
           // existing iterator logic
```

What do you think?

2024-05-28 14:39 UTC, HipsterBrown commented on background_scripts/background.js
> +        section_id: sectionId,
To clarify my understanding, if the menu item ID doesn't contain a section ID, then this field will be set to `undefined` which will omit it from the request body. Is that correct?

2024-05-28 19:57 UTC, Schnouki commented on background_scripts/background.js
> +        .forEach(({ id: sectionId, name: sectionName }, sectionIndex) => {
Sounds good! Will add that shortly.

2024-05-28 20:01 UTC, Schnouki commented on background_scripts/background.js
> +        section_id: sectionId,
Yep! It will be `undefined`, just like `due_string` on the next line, and so will not be included in the JSON body.

2024-05-29 12:17 UTC, HipsterBrown approved these changes

2024-05-29 12:19 UTC, merged

2024-05-29 12:20 UTC, HipsterBrown commented
Thanks again for contributing @Schnouki 🚀 I'll publish a new minor version today.

2024-05-29 14:32 UTC, HipsterBrown commented
@Schnouki Done! v1.12.0 has been published to Firefox Addons 😄